#!/usr/bin/env python3
"""
Authoring source for every level in SILT: Abyss.

Levels are written here as ASCII, then validated and emitted as
app/src/main/java/com/abyss/silt/level/Levels.java.

Run:  python3 tools/levels.py            # validate + generate
      python3 tools/levels.py --check    # validate only

The checks are the point of this file. Each level must prove that:
  * it is structurally sane (one spawn, one exit, matching widths),
  * every gate channel has a switch that something in the level can work,
  * the exit is REACHABLE once the right creatures are used, and
  * the exit is NOT reachable if you take away any creature the level relies
    on - which is what catches a barrier that can simply be swum around.

TERRAIN
  .      open water            #  rock
  k      kelp   (BITER cuts)   r  brittle rock (RAMMER shatters)
  ^v<>   current               T  urchin          J  jelly          P  predator
  S      spawn                 X  exit            C  checkpoint     W  whisper
  B      boss anchor           1..7  BITER RAMMER GLOWER SPARK HEAVY PUFFER LEECH

MECHANISMS - the character carries its own channel, so nothing can drift out of
alignment:
  gates    g = ch1   G = ch2   H = ch3
  plates   p = ch1   q = ch2        (HEAVY only)
  nodes    n = ch1   m = ch2        (SPARK only)
  levers   l = ch1   L = ch2   y = ch3   (BITER or RAMMER)

`bars` fills a whole column with one character after the ASCII is laid out, so a
barrier is always full height and can never be swum around by accident.
"""

import sys
from collections import deque

BITER, RAMMER, GLOWER, SPARK, HEAVY, PUFFER, LEECH = 1, 2, 3, 4, 5, 6, 7

CREATURE_NAMES = {1: "BITER", 2: "RAMMER", 3: "GLOWER", 4: "SPARK",
                  5: "HEAVY", 6: "PUFFER", 7: "LEECH"}

CHAPTERS = [
    "I  ·  THE SHALLOWS",
    "II  ·  THE KELP FOREST",
    "III  ·  THE DARK",
    "IV  ·  THE CIRCUITS",
    "V  ·  THE PRESSURE",
    "VI  ·  THE ABYSS",
]

# Mechanism character -> (engine character, channel)
MECH = {
    "g": ("g", 1), "G": ("g", 2), "H": ("g", 3),
    "p": ("p", 1), "q": ("p", 2),
    "n": ("n", 1), "m": ("n", 2),
    "l": ("l", 1), "L": ("l", 2), "y": ("l", 3),
}

LEVELS = []


def level(title, chapter, art, bars=(), holes=(), hints=(), whispers=(), boss=0,
          dark=0.0, depth=0.0, soft=False, optional=()):
    """soft=True: the challenge is dodging or timing, not topology, so skip the
    "this creature must be required" check entirely.
    optional=[...]: creatures that are deliberately a convenience rather than a
    key - a glower carried for visibility, a rammer offered as an escape."""
    LEVELS.append(dict(title=title, chapter=chapter, art=art, bars=list(bars),
                       holes=list(holes), hints=list(hints),
                       whispers=list(whispers), boss=boss, dark=dark,
                       depth=depth, soft=soft, optional=set(optional)))


# ===================================================================
# CHAPTER I - THE SHALLOWS
# ===================================================================

level("Wake", 1, """
..............................................
..S...........W...............................
......######............######................
....................................#####.....
..#####.......................................
..........########............................
..................................######......
.....######...................................
..............................######..........
...................#######............W.......
...........................................X..
..............................................
""", hints=[
    "Hold your thumb anywhere on the left of the screen. A ring appears - drag it to swim.",
    "The pale ring far to the right is the way down. Swim to it.",
], whispers=[
    "You do not remember going under.",
    "Something ahead is breathing.",
], depth=0.05, soft=True)

level("First Mouth", 1, """
..............................................
..S...........................................
......####............#####..####.............
.................1............................
..#####...........................#####.......
..........#####...............................
..............................................
.....####..........................W..........
..............................................
............####......................####....
...........................................X..
..............................................
""", bars=[(26, "k")], hints=[
    "You cannot cut the weed yourself. But you do not have to be yourself.",
    "Tap the small fish. Your spirit will cross into it.",
    "Wearing the fish, press BITE at the weed. Then press BODY to come home, and swim through.",
], whispers=[
    "The weed does not part for hands.",
], depth=0.1)

level("Bone Wall", 1, """
..............................................
..S...........................................
......####..........#####.....................
..........1...2...............................
..#####.................................W.....
.........#####................................
..............................................
.....####.....................................
..............................................
...........####...................####........
...........................................X..
..............................................
""", bars=[(16, "k"), (30, "r")], hints=[
    "The cracked stone is too thick for teeth. Something has to hit it hard.",
    "The long fish with the spear can DASH. Aim first: a dash cannot be steered.",
    "Two walls, two bodies. Cut the weed with the small one, then take the spear through.",
], whispers=[
    "Cracks, like the ones in your helmet.",
], depth=0.15)

level("Something Circling", 1, """
..............................................
..S...............................C...........
......####...........................####.....
..............2...............................
..#####.................P.....................
.........######...............................
..............................................
.....####.........1...........................
..............................................
...........####.......................####....
...........................................X..
..............................................
""", bars=[(38, "k")], hints=[
    "It hunts whatever your spirit is wearing. It has no interest in an empty body.",
    "A DASH from the spear-fish will stun it for a few seconds. That is enough time.",
    "Or wait: it patrols. Slip past behind it while it swims the other way.",
], whispers=[
    "It has been following since the first dark.",
], depth=0.2, optional=[RAMMER])

level("The Shell", 1, """
..............................................
..S...........................................
......####....................................
..........1...................................
..#####...............................C.......
.........#####................................
..............................................
.....####.........l...........................
..............................................
...........####.......................####....
...........................................X..
..............................................
""", bars=[(14, "k"), (26, "g")], hints=[
    "The shell and the door carry the same mark: one dot each.",
    "Bite the shell open and the door stays open. Cut the weed first to reach it.",
], whispers=[
    "The shell remembers being alive.",
], depth=0.25)


# ===================================================================
# CHAPTER II - THE KELP FOREST
# ===================================================================

level("Undertow", 2, """
..............................................
..S...........................................
......####....>>>>>>>>>>>>....................
..............>>>>>>>>>>>>...........C........
..#####.......>>>>>>>>>>>>....................
..........1...................................
..............................................
.....####.....<<<<<<<<<<<<....................
..............<<<<<<<<<<<<................X...
..............<<<<<<<<<<<<....................
..........................................T...
..############################################
""", bars=[(32, "k")], hints=[
    "The upper flow carries you right. The lower one drags you back.",
    "Ride the top current, then cut down through the weed before it sweeps you.",
    "Keep clear of the spines below the exit.",
], whispers=[
    "The water has opinions here.",
], depth=0.3)

level("Ballast", 2, """
..............................................
..S...................................C.......
......####....................................
..............................................
..#####.......................................
..........#####...............................
..............................................
.....####.................................X...
..................5...........................
..#############...............................
..............p...............................
..############################################
""", bars=[(30, "g")], hints=[
    "The armoured crawler is the only thing heavy enough to hold a plate down.",
    "It cannot swim. It walks the floor and it cannot climb - walk it onto the plate.",
    "STOMP latches the plate for a little while. Send your spirit BODY-ward and swim before it lifts.",
], whispers=[
    "It carries its own grave on its back.",
], depth=0.35)

level("Two Locks", 2, """
..............................................
..S...........................................
......####....................................
..............................................
..#####.........2.........................C...
..........####................................
..............................................
.....####...........................L.........
..............................................
..#########...l...........................X...
..............................................
..############################################
""", bars=[(20, "g"), (30, "r"), (40, "G")], hints=[
    "One dot opens the first door. Two dots open the second.",
    "The two-dot shell is sealed behind cracked stone. Break in before you can reach it.",
    "The spear can do all of it: dash the stone, and a dash trips a shell just as a bite does.",
], whispers=[
    "Two locks. One key. Someone was economical.",
], depth=0.4)

level("Thicket", 2, """
..............................................
..S...........................................
......P.......................................
..............................................
..#####.......................................
............1.................................
..............................................
.....##...............................C.......
..............................................
.....................P....................X...
..............................................
..############################################
""", bars=[(18, "k"), (26, "k"), (34, "k")], hints=[
    "Every curtain of weed needs a bite. There is only one biter - keep it alive.",
    "The hunters chase what you are wearing. Leave the biter, and they lose interest.",
    "Cut a curtain, jump back to your body, let the hunters settle, then cross.",
], whispers=[
    "The forest closes behind you.",
], depth=0.45, dark=0.15)

level("The Maw", 2, """
..............................................
..S...........................................
......####....................................
..............................................
..#####.......2...........B...................
..............................................
..........................................X...
.....####.....................................
..............2...........................C...
..............................................
..#####.......................................
..############################################
""", boss=1, hints=[
    "You cannot outswim it. Watch the eye - it only opens after it lunges.",
    "Wear a spear-fish. When the eye opens, DASH straight into it.",
    "A dash cannot turn. Line yourself up before the eye opens, not after.",
], whispers=[
    "It has been waiting the whole way down.",
], depth=0.5, dark=0.20, soft=True)


# ===================================================================
# CHAPTER III - THE DARK
# ===================================================================

level("Blind", 3, """
..............................................
..S...........................................
......####........T.........T.................
..............................................
..#####...3...................................
..........................T.........C.........
..................T...........................
.....####...................T.............X...
..............................................
...........####......T....................T...
..............................................
..############################################
""", hints=[
    "You carry a lamp, but it barely reaches. Something down here carries a better one.",
    "The pale fish with the lure lights a wide circle. Wear it and the spines become visible.",
    "FLARE throws light much further for a moment. Use it to read the room before you move.",
], whispers=[
    "The dark is not empty. It is only patient.",
], depth=0.55, dark=0.88, soft=True)

level("Lantern and Teeth", 3, """
..............................................
..S...........................................
......####............P.......................
..............................................
..#####...3...................................
..........................................C...
..............T...........T...................
.....####.................................X...
..............................................
...........####.......P.......................
..............................................
..############################################
""", hints=[
    "The lure fish is bright, and bright things are noticed.",
    "FLARE does not only light the room. It drives hunters away for a few seconds.",
    "Flare, then swim. Do not wait for the light to fade before you move.",
], whispers=[
    "They hunt by the shape you make in the water.",
], depth=0.6, dark=0.9, soft=True)

level("Deadfall", 3, """
..............................................
..S...........................................
......####........T...........................
..............................................
..#####...3.........................C.........
..............T...............................
..........2...................................
.....####.................................X...
..............T...........................T...
...........####...............................
..............................................
..############################################
""", bars=[(28, "r")], hints=[
    "Two bodies, two jobs. One to see with, one to break with.",
    "Light the wall first so you know where to aim, then swap to the spear.",
    "Your spirit can jump straight from one fish to another if they are close enough.",
], whispers=[
    "Bone, mostly. Some of it recent.",
], depth=0.62, dark=0.9, optional=[GLOWER])

level("The Long Vent", 3, """
..............................................
..S...........................................
......####....^^^^....................C.......
..............^^^^............................
..#####...3...^^^^............................
..............^^^^............................
..............^^^^........................X...
.....####.....^^^^............................
..........2...^^^^............................
...........####...............T...............
..............................................
..############################################
""", bars=[(26, "r")], hints=[
    "The vent pushes everything upward, including you.",
    "Cross the vent low, where the rock narrows it, or let it carry you and steer out at the top.",
    "The cracked wall on the far side still needs a dash. Bring the spear across the vent.",
], whispers=[
    "Warm. The first warm thing in a long time.",
], depth=0.65, dark=0.85, optional=[GLOWER])

level("Chorus", 3, """
..............................................
..S...........................................
......####....................................
..............1...............................
..#####...3...................................
..........####....................C...........
..............................................
.....####.................................X...
..........5...................................
..#########.......l...........................
..........p...................................
..############################################
""", bars=[(30, "g")], hints=[
    "The door has one dot. So do both switches below it - it needs BOTH of them at once.",
    "The shell stays open once bitten. The plate does not: it lifts after a while.",
    "Open the shell first. Then stomp the plate, recall your spirit, and swim.",
], whispers=[
    "Two voices, one note.",
], depth=0.7, dark=0.88, optional=[GLOWER])


# ===================================================================
# CHAPTER IV - THE CIRCUITS
# ===================================================================

level("Static", 4, """
..............................................
..S...........................................
......####....................................
..............4...............................
..#####...........................C...........
..........####................................
..................n.......................X...
.....####.....................................
..............................................
..#########...................................
..............................................
..############################################
""", bars=[(26, "g")], hints=[
    "The eel carries a charge. The ring on the wall is waiting for one.",
    "Swim the eel close to the ring and press SHOCK.",
    "The charge drains. Get your body moving before the door falls again.",
], whispers=[
    "Someone built this. That is worse.",
], depth=0.55, dark=0.4)

level("Relay", 4, """
..............................................
..S...........................................
......####....n...............................
..............................................
..#####.......................................
..........4...................................
..............................C...........X...
.....####.............n.......................
..............................................
..#########...................................
..............................................
..############################################
""", bars=[(34, "g")], hints=[
    "Both rings carry one dot, and so does the door. One dot lit is not enough.",
    "A charged ring holds for about ten seconds. That is your whole budget.",
    "Shock the far ring first, then race back and shock the near one - then recall and swim.",
], whispers=[
    "Ten seconds is a long time and no time at all.",
], depth=0.6, dark=0.45)

level("Cathode", 4, """
..............................................
..S...........................................
......####....................................
..............4...............................
..#####.......................................
..........####................................
..............................m...........X...
.....####.................................C...
..........5...................................
..#########...................................
..........p...................................
..############################################
""", bars=[(22, "g"), (38, "G")], hints=[
    "Two doors, two marks. Read the dots under each switch.",
    "The plate holds the first door. The ring holds the second.",
    "Stomp, swim through the first door, then charge the ring from the far side.",
], whispers=[
    "Doors in sequence. A corridor built to be survived, not enjoyed.",
], depth=0.62, dark=0.5)

level("Unnoticed", 4, """
..............................................
..S...........................................
......####....................................
..............7...............................
..####################################........
..........P.......P...............P...........
.........................1l...................
..####################################........
......................................C.......
..#########...................................
..........................................X...
..############################################
""", bars=[(40, "g")], hints=[
    "The gallery is sealed but for its far end, and three hunters live inside it.",
    "The pale worm is a parasite. Hunters do not register it at all - it swims straight past them.",
    "Take the worm down the gallery to the shell, then jump your spirit into the biter beside it.",
], whispers=[
    "It does not notice you at all. That is the whole trick.",
], depth=0.65, dark=0.4, soft=True)

level("The Crawler", 4, """
..............................................
..S...........................................
......####....................................
..............2...............................
..#####.......................................
......................B...................X...
..............................................
.....####.....2...............................
..............................C...............
..#####.......................................
..............2...............................
..############################################
""", boss=2, hints=[
    "This one circles instead of hovering. It spits before it strikes.",
    "The spat drifters kill on contact. Put rock between you and them.",
    "Same rule as the last one: the eye opens only after the lunge. Be lined up already.",
], whispers=[
    "It has too many segments to count while it is moving.",
], depth=0.7, dark=0.34, soft=True)


# ===================================================================
# CHAPTER V - THE PRESSURE
# ===================================================================

level("Rise", 5, """
..............................................
..S...................#########...............
......####............#...1...#...............
......................#...l...#...............
..#####...............#.......#.......C.......
..........####........#vvvvvvv#...........X...
......................#vvvvvvv#...............
.....####.............#vvvvvvv#...............
..........6...........#vvvvvvv#...............
..#########...........#vvvvvvv#...............
......................vvvvvvvvv...............
..############################################
""", bars=[(34, "g")], hints=[
    "The shaft pours downward. Anything that swims gets pushed straight back out.",
    "The round fish can swallow water. INFLATE and the current stops mattering to it - it rises anyway.",
    "There is a biter waiting in the top chamber. Jump your spirit into it and take the shell.",
], whispers=[
    "Everything down here is trying to sink.",
], depth=0.72, dark=0.5, soft=True)

level("Ballast and Breath", 5, """
..............................................
..S...........................................
......####....................................
..............6...............................
..#####...............................C.......
..........####................................
..........................^^^.............X...
.....####.................^^^.................
..........5...............^^^.................
..#########...............^^^.................
..........p...............^^^.................
..############################################
""", bars=[(22, "g")], hints=[
    "Only the crawler can work the plate, and the plate does not stay down long.",
    "Your body is slow. Position it at the door before you go and stomp.",
    "The vent past the door pushes up. Let it carry you; do not fight it.",
], whispers=[
    "You are getting good at leaving yourself behind.",
], depth=0.75, dark=0.55, optional=[PUFFER])

level("Needle Gallery", 5, """
..............................................
..S...........................................
......####....T...T...T...T...T...T...........
..............................................
..#####.......................................
..........6...................................
..............................................
.....####.....T...T...T...T...T...T.......X...
..............................................
..#####...................................C...
..............T...T...T...T...T...T...........
..############################################
""", hints=[
    "Inflated, you are large and slow. Deflated, you are small and quick.",
    "The gaps between the spines are narrower than an inflated body.",
    "Stay small through the gallery. Inflating here only makes you a bigger target.",
], whispers=[
    "A room designed by something with a sense of humour.",
], depth=0.78, dark=0.6, soft=True)

level("The Hive", 5, """
..............................................
..S...........J.......J.......................
......####....................C...............
..............................................
..#####...3.......J...........................
..........................................X...
..............................................
.....####.....J.......J.......................
..............................................
..#####...4...................................
..................n...........................
..############################################
""", bars=[(34, "g")], hints=[
    "The drifting bells kill anything that touches them, and they never stop moving.",
    "The lure fish lights them up long before you reach them. Map the room, then move.",
    "The ring near the floor needs the eel. Time the crossing between bells.",
], whispers=[
    "They pulse together. Something is counting for them.",
], depth=0.8, dark=0.85, optional=[GLOWER])

level("Convergence", 5, """
..............................................
..S...........................................
......####....................................
..............................................
..#####.......................................
..........####........................C.......
..........................................X...
.....####.....................................
..............................................
........5.......4.........1...................
........p.......m.........y...................
..############################################
""", bars=[(14, "g"), (22, "G"), (34, "H")], hints=[
    "Three doors, three marks: one dot, two dots, three dots. Match each to its switch.",
    "The plate is one dot, the ring is two dots, the shell is three.",
    "The plate and the ring both time out. Do the shell first - it stays open.",
], whispers=[
    "Everything narrows toward the same throat.",
], depth=0.85, dark=0.7)


# ===================================================================
# CHAPTER VI - THE ABYSS
# ===================================================================

level("Trench", 6, """
..............................................
..S...........................................
......####....vvvv............................
..............vvvv....P.......................
..#####...3...vvvv............................
..............vvvv............C...1...........
..............vvvv............................
.....####.....vvvv........T.......T.......X...
..............vvvv............................
..#####...7...vvvv....P.......................
..............vvvv............................
..############################################
""", bars=[(38, "k")], hints=[
    "The downdraft is faster than anything you can wear.",
    "Hunters ignore the worm completely. Cross low, wearing it.",
    "Light first, then swim. Do not enter the trench without knowing where the spines are.",
], whispers=[
    "Down is easy. Down is the only easy thing.",
], depth=0.9, dark=0.85, soft=True)

level("Whalefall", 6, """
..............................................
..S...........................................
......####....................................
..............................................
..#####...2...................C...............
..............................................
..........P...............................X...
.....####.....................................
..............................................
..................5...........................
..............................p...............
..############################################
""", bars=[(16, "r"), (22, "r"), (38, "g")], hints=[
    "The crawler is sealed inside the ribcage, and the plate is outside it.",
    "Break a rib low down, at the floor, so the crawler can walk out through the gap.",
    "It cannot climb. Everything it does has to happen along the seabed.",
], whispers=[
    "Something enormous died here and fed everything else for a century.",
], depth=0.92, dark=0.8)

level("The Choir", 6, """
..............................................
..S...........................................
......####n...................................
..............................................
..#####.......4...............................
..........####................1...............
..........................................X...
.....####.........n...........................
..............................L...............
..#########...................................
.....................................C........
..############################################
""", bars=[(22, "g"), (38, "G")], hints=[
    "The first door needs both rings lit at the same time, and each ring fades.",
    "Shock the lower ring, then get to the upper one before the first goes dark.",
    "The far door needs the two-dot shell, and that shell is behind the first door.",
], whispers=[
    "They sing to keep the doors shut.",
], depth=0.94, dark=0.85)

level("Threshold", 6, """
..............................................
..S...........................................
......####....................................
..............1...............................
..#####...2...................................
..............................................
..............................................
.....####.............................C.......
..........5...............................X...
..#########...................................
..............p...........................T...
..############################################
""", bars=[(18, "k"), (26, "g"), (34, "r")], hints=[
    "Everything you have learned, in order: cut, weigh, break.",
    "The weed comes down first - the crawler cannot walk through it.",
    "The plate is timed. Leave your body past the door before you stomp.",
], whispers=[
    "The last door before the floor of the world.",
], depth=0.96, dark=0.8)

level("The Abyssal", 6, """
..............................................
..S...........................................
......####....................................
..............2...............................
..#####.......................................
..............................B...........X...
..........####................................
.....####.....2...............................
..............................C...............
..#####.......................................
..............2...............................
..############################################
""", boss=3, hints=[
    "Five hits. It spits constantly and its lunge crosses the whole room.",
    "There are three spear-fish. If one dies it comes back - you are never out of options.",
    "Do not chase the eye. Pick your lane, wait for the lunge to end, and dash straight.",
], whispers=[
    "It does not hunt you. It simply lives here, and you are inside it.",
], depth=1.0, dark=0.42, soft=True)


# ===================================================================
# build + validate
# ===================================================================

CREATURE_CHARS = set("1234567")
SWITCH_CHARS = set("pqnmlLy")
GATE_CHARS = set("gGH")


def build(lv):
    """Apply bars/holes, pad, wrap in rock, and split into terrain + wire."""
    rows = [r for r in lv["art"].split("\n") if r != ""]
    w = max(len(r) for r in rows)
    grid = [list(r.ljust(w, ".")) for r in rows]

    clobbered = []
    for col, ch in lv["bars"]:
        for r in range(len(grid)):
            was = grid[r][col]
            if was == "#":
                continue            # rock already blocks; leave it alone
            if was != ".":
                clobbered.append((col, r, was))
            grid[r][col] = ch
    lv["_clobbered"] = clobbered
    for col, row in lv["holes"]:
        grid[row][col] = "."

    terrain, wire = [], []
    for r in range(len(grid)):
        trow, wrow = [], []
        for c in range(w):
            ch = grid[r][c]
            if ch in MECH:
                base, chan = MECH[ch]
                trow.append(base)
                wrow.append(str(chan))
            else:
                trow.append(ch)
                wrow.append(" ")
        terrain.append("".join(trow))
        wire.append("".join(wrow))

    border = "#" * (w + 4)
    terrain = [border] + ["##" + r + "##" for r in terrain] + [border]
    blank = " " * (w + 4)
    wire = [blank] + ["  " + r + "  " for r in wire] + [blank]
    has_wire = any(ch.isdigit() for r in wire for ch in r)
    return terrain, (wire if has_wire else None)


def channel_at(wire, c, r):
    if not wire or r >= len(wire) or c >= len(wire[r]):
        return 0
    ch = wire[r][c]
    return int(ch) if ch.isdigit() else 0


def passable(ch, creatures, open_ch, chan):
    if ch == "#":
        return False
    if ch == "k":
        return BITER in creatures
    if ch == "r":
        return RAMMER in creatures
    if ch == "g":
        return chan in open_ch
    return True


def flood(terrain, wire, start, creatures, open_ch):
    h, w = len(terrain), len(terrain[0])
    seen = {start}
    q = deque([start])
    while q:
        c, r = q.popleft()
        for dc, dr in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nc, nr = c + dc, r + dr
            if not (0 <= nc < w and 0 <= nr < h) or (nc, nr) in seen:
                continue
            if passable(terrain[nr][nc], creatures, open_ch, channel_at(wire, nc, nr)):
                seen.add((nc, nr))
                q.append((nc, nr))
    return seen


def heavy_reach(terrain, wire, starts, creatures, open_ch):
    """Where a HEAVY can get: walk sideways, fall, never climb."""
    h, w = len(terrain), len(terrain[0])

    def openc(c, r):
        if not (0 <= c < w and 0 <= r < h):
            return False
        return passable(terrain[r][c], creatures, open_ch, channel_at(wire, c, r))

    def settle(c, r):
        while openc(c, r + 1):
            r += 1
        return c, r

    seen, q = set(), deque()
    for s in starts:
        p = settle(*s)
        seen.add(p)
        q.append(p)
    while q:
        c, r = q.popleft()
        for dc in (1, -1):
            if openc(c + dc, r):
                p = settle(c + dc, r)
                if p not in seen:
                    seen.add(p)
                    q.append(p)
    return seen


def positions_of(terrain):
    pos = {}
    for r, row in enumerate(terrain):
        for c, ch in enumerate(row):
            pos.setdefault(ch, []).append((c, r))
    return pos


def solve(terrain, wire, pos, banned=()):
    """Fixpoint: which creatures can be reached, which channels open, and is the
    exit reachable? Returns (reachable_set, creatures, open_channels)."""
    start = pos["S"][0]
    creatures, open_ch = set(), set()

    for _ in range(24):
        reach = flood(terrain, wire, start, creatures, open_ch)
        grew = False

        for ch in CREATURE_CHARS:
            t = int(ch)
            if t in banned:
                continue
            for p in pos.get(ch, []):
                if p in reach and t not in creatures:
                    creatures.add(t)
                    grew = True

        heavy_cells = set()
        if HEAVY in creatures:
            starts = [p for p in pos.get("5", []) if p in reach]
            if starts:
                heavy_cells = heavy_reach(terrain, wire, starts, creatures, open_ch)

        by_channel = {}
        for kind in "pnl":
            for p in pos.get(kind, []):
                chan = channel_at(wire, p[0], p[1])
                ok = False
                if p in reach:
                    if kind == "p":
                        ok = HEAVY in creatures and p in heavy_cells
                    elif kind == "n":
                        ok = SPARK in creatures
                    else:
                        ok = BITER in creatures or RAMMER in creatures
                by_channel.setdefault(chan, []).append(ok)

        for chan, oks in by_channel.items():
            if all(oks) and chan not in open_ch:
                open_ch.add(chan)
                grew = True

        if not grew:
            break

    return flood(terrain, wire, start, creatures, open_ch), creatures, open_ch


def analyse(lv):
    terrain, wire = build(lv)
    h, w = len(terrain), len(terrain[0])
    errs, warns = [], []

    pos = positions_of(terrain)
    counts = {ch: len(v) for ch, v in pos.items()}

    for r in range(h):
        if len(terrain[r]) != w:
            errs.append(f"row {r} width {len(terrain[r])} != {w}")

    if counts.get("S", 0) != 1:
        errs.append(f"need exactly 1 'S', found {counts.get('S', 0)}")
    if counts.get("X", 0) != 1:
        errs.append(f"need exactly 1 'X', found {counts.get('X', 0)}")
    if lv["boss"] and counts.get("B", 0) != 1:
        errs.append("boss level needs exactly one 'B'")
    if not lv["boss"] and counts.get("B", 0):
        errs.append("'B' present but boss id is 0")
    for (c, r, was) in lv.get("_clobbered", []):
        errs.append(f"bar at column {c} overwrote '{was}' on row {r}")
    if counts.get("W", 0) > len(lv["whispers"]):
        warns.append(f"{counts.get('W', 0)} whisper markers, {len(lv['whispers'])} lines")
    if not lv["hints"]:
        warns.append("no hints authored")

    # Gate/switch wiring.
    gate_ch = {channel_at(wire, c, r) for (c, r) in pos.get("g", [])}
    sw_ch = set()
    for kind in "pnl":
        for (c, r) in pos.get(kind, []):
            sw_ch.add(channel_at(wire, c, r))
    for gc in sorted(gate_ch):
        if gc not in sw_ch:
            errs.append(f"gate channel {gc} has no switch")
    for sc in sorted(sw_ch):
        if sc not in gate_ch:
            warns.append(f"switch channel {sc} drives no gate")

    # Required creature per mechanism.
    if counts.get("k") and not counts.get("1"):
        errs.append("kelp but no BITER")
    if counts.get("r") and not counts.get("2"):
        errs.append("brittle rock but no RAMMER")
    if counts.get("p") and not counts.get("5"):
        errs.append("plate but no HEAVY")
    if counts.get("n") and not counts.get("4"):
        errs.append("node but no SPARK")
    if counts.get("l") and not (counts.get("1") or counts.get("2")):
        errs.append("lever but no BITER or RAMMER")

    if errs:
        return errs, warns

    exit_pos = pos["X"][0]
    reach, creatures, open_ch = solve(terrain, wire, pos)
    if exit_pos not in reach:
        errs.append("EXIT UNREACHABLE - level cannot be finished")
        return errs, warns

    for ch in CREATURE_CHARS:
        if ch in counts and int(ch) not in creatures:
            warns.append(f"{CREATURE_NAMES[int(ch)]} is present but never reachable")

    # Necessity: taking away a creature the level provides should break it.
    if not lv["soft"]:
        for t in sorted(creatures - lv["optional"]):
            reach2, _, _ = solve(terrain, wire, pos, banned={t})
            if exit_pos in reach2:
                warns.append(f"{CREATURE_NAMES[t]} is not required - "
                             "is there a way around its barrier?")

    return errs, warns


# ===================================================================
# emit
# ===================================================================

def jstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit():
    o = []
    a = o.append
    a("package com.abyss.silt.level;\n")
    a("/**")
    a(" * Generated by tools/levels.py - do not edit by hand.")
    a(" * Every level below has passed that script's structural, solvability and")
    a(" * necessity checks, including a reachability proof for the exit.")
    a(" */")
    a("public final class Levels {\n")
    a("    private Levels() {}\n")
    a("    private static final String[] CHAPTER_TITLES = {")
    for t in CHAPTERS:
        a(f"        {jstr(t)},")
    a("    };\n")
    a("    public static String chapterTitle(int chapter) {")
    a("        int i = chapter - 1;")
    a("        return (i >= 0 && i < CHAPTER_TITLES.length) ? CHAPTER_TITLES[i] : \"\";")
    a("    }\n")
    a("    private static final LevelDef[] ALL = {")
    for i, lv in enumerate(LEVELS):
        terrain, wire = build(lv)
        a("        new LevelDef(%d, %d, %s," % (i, lv["chapter"], jstr(lv["title"])))
        a("            new String[]{")
        for r in terrain:
            a(f"                {jstr(r)},")
        a("            },")
        if wire:
            a("            new String[]{")
            for r in wire:
                a(f"                {jstr(r)},")
            a("            },")
        else:
            a("            null,")
        a("            new String[]{")
        for hnt in lv["hints"]:
            a(f"                {jstr(hnt)},")
        a("            },")
        a("            new String[]{")
        for wh in lv["whispers"]:
            a(f"                {jstr(wh)},")
        a("            },")
        a("            %d).lit(%.2ff, %.2ff)," % (lv["boss"], lv["dark"], lv["depth"]))
    a("    };\n")
    a("    public static int count() {")
    a("        return ALL.length;")
    a("    }\n")
    a("    public static LevelDef get(int i) {")
    a("        if (i < 0) i = 0;")
    a("        if (i >= ALL.length) i = ALL.length - 1;")
    a("        return ALL[i];")
    a("    }")
    a("}")
    return "\n".join(o) + "\n"


def assign_depths():
    """Depth is the descent, so it is derived from position in the run rather
    than hand-typed - that way it can never go backwards between chapters."""
    n = len(LEVELS)
    for i, lv in enumerate(LEVELS):
        lv["depth"] = round(0.05 + 0.95 * i / (n - 1), 3)


def main():
    assign_depths()
    errors = 0
    for i, lv in enumerate(LEVELS):
        errs, warns = analyse(lv)
        tag = f"[{i + 1:2d}] {lv['title']:<20}"
        errors += len(errs)
        for e in errs:
            print(f"{tag} ERROR  {e}")
        for wn in warns:
            print(f"{tag} warn   {wn}")
        if not errs and not warns:
            print(f"{tag} ok")

    print(f"\n{len(LEVELS)} levels, {errors} errors")
    if errors:
        return 1
    if "--check" not in sys.argv:
        path = "app/src/main/java/com/abyss/silt/level/Levels.java"
        with open(path, "w") as f:
            f.write(emit())
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
