plugins {
    id 'com.android.application'
}

android {
    namespace 'com.b1wortschatz.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.b1wortschatz.app"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("release.keystore")
            storePassword "b1wortschatz"
            keyAlias "b1key"
            keyPassword "b1wortschatz"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
